name: Docker Build and Push

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  docker-build:
    runs-on: [default]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and Save Docker Tag
        run: |
          echo "DOCKER_TAG1=${{ github.repository }}:${GITHUB_REF#refs/heads/}-${{ github.run_id }}" >> $GITHUB_ENV
          echo "DOCKER_TAG2=${{ github.repository }}:${GITHUB_REF#refs/heads/}-${{ github.run_id }}" >> $GITHUB_ENV
          echo "DOCKER_TAG3=${{ github.ref_name }}-${{ github.run_id }}" >> $GITHUB_ENV
          echo $DOCKER_TAG3
          export


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: $DOCKER_TAG3
