on: [push]

jobs:
  publish:
    runs-on: [self-hosted, linux, X64]
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Print GitHub context variables
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "${{ vars.CF_ACCOUNT_ID }}"
          echo "${{ vars.GITHUB_REPOSITORY }}"

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          projectName: ${{ github.ref_name }}
          wranglerVersion: "3"
          directory: "build"
