on: [push]

jobs:
  publish:
    runs-on: [self-hosted, linux, X64]
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ var.CF_ACCOUNT_ID }}
          projectName: ${{ github.head_ref }}
          wranglerVersion: "3"
          directory: "build"
